service: frish

image: frish

servers:
  web:
    hosts:
      - 35.154.124.179

# Credentials for your image host.
registry:
  server: 590184052210.dkr.ecr.ap-south-1.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>

env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: ubuntu

builder:
  args:
    RUBY_VERSION: 3.3.1
    RAILS_ENV: production
    NODE_VERSION: 22.1.0
    YARN_VERSION: 1.22.19
  multiarch: false
  
# accessories:
#   db:
#     image: postgres:16.0
#     host: 35.154.124.179
#     port: 5432
#     directories:
#       - data:/var/lib/postgresql/data